// <auto-generated />
using System;
using FrozenApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FrozenApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251115131422_FreshInitialMigration")]
    partial class FreshInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FrozenApi.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ResolvedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("IsResolved");

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("Type");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("FrozenApi.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FrozenApi.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("CreditLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PendingBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BYTEA")
                        .HasDefaultValue(new byte[] { 0 });

                    b.Property<decimal>("TotalPayments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalSales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Trn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FrozenApi.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("FrozenApi.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExpenseCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#EF4444",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 187, DateTimeKind.Utc).AddTicks(3827),
                            IsActive = true,
                            Name = "Rent"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#F59E0B",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 187, DateTimeKind.Utc).AddTicks(4152),
                            IsActive = true,
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#3B82F6",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 187, DateTimeKind.Utc).AddTicks(4154),
                            IsActive = true,
                            Name = "Staff Salary"
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#8B5CF6",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 187, DateTimeKind.Utc).AddTicks(4157),
                            IsActive = true,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "#14B8A6",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 187, DateTimeKind.Utc).AddTicks(4159),
                            IsActive = true,
                            Name = "Fuel"
                        },
                        new
                        {
                            Id = 6,
                            ColorCode = "#F97316",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 187, DateTimeKind.Utc).AddTicks(4161),
                            IsActive = true,
                            Name = "Delivery"
                        },
                        new
                        {
                            Id = 7,
                            ColorCode = "#EC4899",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 187, DateTimeKind.Utc).AddTicks(4409),
                            IsActive = true,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 8,
                            ColorCode = "#6366F1",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 187, DateTimeKind.Utc).AddTicks(4411),
                            IsActive = true,
                            Name = "Maintenance"
                        },
                        new
                        {
                            Id = 9,
                            ColorCode = "#10B981",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 187, DateTimeKind.Utc).AddTicks(4413),
                            IsActive = true,
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 10,
                            ColorCode = "#6B7280",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 187, DateTimeKind.Utc).AddTicks(4415),
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("FrozenApi.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChangeQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int?>("RefId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("FrozenApi.Models.InvoiceTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CssCode")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("HtmlCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsActive");

                    b.ToTable("InvoiceTemplates");
                });

            modelBuilder.Entity("FrozenApi.Models.InvoiceVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiffSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EditReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SaleId");

                    b.HasIndex("SaleId", "VersionNumber");

                    b.ToTable("InvoiceVersions");
                });

            modelBuilder.Entity("FrozenApi.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int?>("SaleId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SaleId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FrozenApi.Models.PaymentIdempotency", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseSnapshot")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("IdempotencyKey");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentIdempotencies");
                });

            modelBuilder.Entity("FrozenApi.Models.PriceChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("integer");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceDifference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("ProductId");

                    b.ToTable("PriceChangeLogs");
                });

            modelBuilder.Entity("FrozenApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConversionToBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[] { 0 });

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("StockQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConversionToBase = 1m,
                            CostPrice = 75.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(5493),
                            DescriptionEn = "Frozen chicken griller 1000gm per carton",
                            NameAr = "دجاج شواء مجمد 1000جم - كواليكو",
                            NameEn = "FROZEN CHICKEN GRILLER 1000GM - QUALIKO",
                            ReorderLevel = 3,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 86.00m,
                            Sku = "CHK-GRL-001",
                            StockQty = 7m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(6029)
                        },
                        new
                        {
                            Id = 2,
                            ConversionToBase = 1m,
                            CostPrice = 85.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(7163),
                            DescriptionEn = "Frozen chicken grillers 10x1200gms per carton",
                            NameAr = "دجاج شواء مجمد (10×1200جم) - فرانجوسول",
                            NameEn = "FROZEN CHICKEN GRILLERS (10X1200GMS)-FRANGOSUL",
                            ReorderLevel = 3,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 99.00m,
                            Sku = "CHK-GRL-002",
                            StockQty = 5m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(7165)
                        },
                        new
                        {
                            Id = 3,
                            ConversionToBase = 1m,
                            CostPrice = 60.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(7857),
                            DescriptionEn = "Frozen chicken grillers 10x900gms per carton",
                            NameAr = "دجاج شواء مجمد (10×900جم) - سيدروب",
                            NameEn = "FROZEN CHICKEN GRILLERS (10X900GMS)-CEDROB",
                            ReorderLevel = 3,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 70.00m,
                            Sku = "CHK-GRL-003",
                            StockQty = 1m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(7863)
                        },
                        new
                        {
                            Id = 4,
                            ConversionToBase = 1m,
                            CostPrice = 125.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(7889),
                            DescriptionEn = "Frozen chicken breast skinless boneless 12kgs",
                            NameAr = "صدر دجاج مجمد بدون جلد/عظم - بركات 12كجم",
                            NameEn = "FROZEN CHICKEN BREAST S/L B/L - BARKAT 12KGS",
                            ReorderLevel = 2,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 145.00m,
                            Sku = "CHK-BREAST-001",
                            StockQty = 1m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(7890)
                        },
                        new
                        {
                            Id = 5,
                            ConversionToBase = 1m,
                            CostPrice = 28.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(7896),
                            DescriptionEn = "Frozen tapioca cuts 12x700gm per carton",
                            NameAr = "تأبيوكا مقطعة مجمدة - مالابار (12×700 جم)",
                            NameEn = "FROZEN-TAPIOCA CUTS-MALABAR (12X700 GM)",
                            ReorderLevel = 3,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 33.00m,
                            Sku = "VEG-TAP-001",
                            StockQty = 4m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(7897)
                        },
                        new
                        {
                            Id = 6,
                            ConversionToBase = 1m,
                            CostPrice = 250.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(7901),
                            DescriptionEn = "Frozen Indian bobby veal 18kg per carton",
                            NameAr = "لحم عجل هندي بوبي مجمد 18كجم - برايم جولد",
                            NameEn = "FROZEN INDIAN BOBBY VEAL 18KG- PRIME GOLD",
                            ReorderLevel = 1,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 275.00m,
                            Sku = "BEEF-BOB-001",
                            StockQty = 1m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(7902)
                        },
                        new
                        {
                            Id = 7,
                            ConversionToBase = 1m,
                            CostPrice = 250.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(7906),
                            DescriptionEn = "Veal leg",
                            NameAr = "لحم عجل ساق أمين",
                            NameEn = "VEAL LEG AMEEN",
                            ReorderLevel = 5,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 305.00m,
                            Sku = "MEAT-VEAL-001",
                            StockQty = 15m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(7907)
                        },
                        new
                        {
                            Id = 8,
                            ConversionToBase = 1m,
                            CostPrice = 75.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(7911),
                            DescriptionEn = "Hamoor fillet",
                            NameAr = "هامور فيليه",
                            NameEn = "HAMOOR FILLET",
                            ReorderLevel = 5,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 88.00m,
                            Sku = "SEA-HAMOOR-001",
                            StockQty = 20m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(7912)
                        },
                        new
                        {
                            Id = 9,
                            ConversionToBase = 1m,
                            CostPrice = 85.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8203),
                            DescriptionEn = "1200 gm chicken",
                            NameAr = "دجاج 1200 جم",
                            NameEn = "1200 GM CKN",
                            ReorderLevel = 10,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 98.00m,
                            Sku = "CHK-1200GM-001",
                            StockQty = 30m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8205)
                        },
                        new
                        {
                            Id = 10,
                            ConversionToBase = 1m,
                            CostPrice = 95.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8216),
                            DescriptionEn = "1300 gm chicken",
                            NameAr = "دجاج 1300 جم",
                            NameEn = "1300 GM CKN",
                            ReorderLevel = 10,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 112.00m,
                            Sku = "CHK-1300GM-001",
                            StockQty = 25m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8216)
                        },
                        new
                        {
                            Id = 11,
                            ConversionToBase = 1m,
                            CostPrice = 150.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8252),
                            DescriptionEn = "Chicken breast 12kg",
                            NameAr = "صدر 12 كجم",
                            NameEn = "BREAST 12KG",
                            ReorderLevel = 5,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 179.00m,
                            Sku = "CHK-BREAST-12KG",
                            StockQty = 12m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8265)
                        },
                        new
                        {
                            Id = 12,
                            ConversionToBase = 1m,
                            CostPrice = 45.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8270),
                            DescriptionEn = "Mumtaz butter",
                            NameAr = "زبدة ممتاز",
                            NameEn = "MUMTAZ BUTTER",
                            ReorderLevel = 10,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 56.00m,
                            Sku = "DAIRY-BUTTER-001",
                            StockQty = 40m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8273)
                        },
                        new
                        {
                            Id = 13,
                            ConversionToBase = 1m,
                            CostPrice = 115.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8282),
                            DescriptionEn = "Chicken breast 12kg aroura",
                            NameAr = "صدر 12 كجم أورورا",
                            NameEn = "BREAST 12KG AROURA",
                            ReorderLevel = 5,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 140.00m,
                            Sku = "CHK-BREAST-AROURA",
                            StockQty = 18m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8284)
                        },
                        new
                        {
                            Id = 14,
                            ConversionToBase = 1m,
                            CostPrice = 150.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8291),
                            DescriptionEn = "Meat mince",
                            NameAr = "لحم مفروم",
                            NameEn = "MEAT MINCE",
                            ReorderLevel = 5,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 180.00m,
                            Sku = "MEAT-MINCE-001",
                            StockQty = 15m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8292)
                        },
                        new
                        {
                            Id = 15,
                            ConversionToBase = 1m,
                            CostPrice = 75.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8297),
                            DescriptionEn = "1000 gm chicken",
                            NameAr = "دجاج 1000 جم",
                            NameEn = "1000GM CKN",
                            ReorderLevel = 10,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 88.00m,
                            Sku = "CHK-1000GM-001",
                            StockQty = 35m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8298)
                        },
                        new
                        {
                            Id = 16,
                            ConversionToBase = 1m,
                            CostPrice = 85.00m,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8302),
                            DescriptionEn = "Rose hotdog",
                            NameAr = "هوت دوغ روز",
                            NameEn = "ROSE HOTDOG",
                            ReorderLevel = 10,
                            RowVersion = new byte[] { 0 },
                            SellPrice = 103.00m,
                            Sku = "FOOD-HOTDOG-001",
                            StockQty = 45m,
                            UnitType = "CRTN",
                            UpdatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 186, DateTimeKind.Utc).AddTicks(8302)
                        });
                });

            modelBuilder.Entity("FrozenApi.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("ExpenseCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InvoiceFileName")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceFilePath")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("InvoiceNo")
                        .IsUnique();

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("FrozenApi.Models.PurchaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("FrozenApi.Models.PurchaseReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReturnNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<decimal>("VatTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("ReturnNo")
                        .IsUnique();

                    b.ToTable("PurchaseReturns");
                });

            modelBuilder.Entity("FrozenApi.Models.PurchaseReturnItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseReturnId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseItemId");

                    b.HasIndex("PurchaseReturnId");

                    b.ToTable("PurchaseReturnItems");
                });

            modelBuilder.Entity("FrozenApi.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EditReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("PaidAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[] { 0 });

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ExternalReference")
                        .IsUnique()
                        .HasFilter("\"ExternalReference\" IS NOT NULL");

                    b.HasIndex("InvoiceNo")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("IsLocked");

                    b.HasIndex("LastModifiedBy");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("FrozenApi.Models.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("FrozenApi.Models.SaleReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsBadItem")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("RestoreStock")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReturnNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReturnNo")
                        .IsUnique();

                    b.HasIndex("SaleId");

                    b.ToTable("SaleReturns");
                });

            modelBuilder.Entity("FrozenApi.Models.SaleReturnItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SaleItemId")
                        .HasColumnType("integer");

                    b.Property<int>("SaleReturnId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleItemId");

                    b.HasIndex("SaleReturnId");

                    b.ToTable("SaleReturnItems");
                });

            modelBuilder.Entity("FrozenApi.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Key = "VAT_PERCENT",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 181, DateTimeKind.Utc).AddTicks(9960),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "5"
                        },
                        new
                        {
                            Key = "COMPANY_NAME_EN",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 182, DateTimeKind.Utc).AddTicks(7283),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "Starplus Foodstuff Trading"
                        },
                        new
                        {
                            Key = "COMPANY_NAME_AR",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 182, DateTimeKind.Utc).AddTicks(7290),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "ستار بلس لتجارة المواد الغذائية"
                        },
                        new
                        {
                            Key = "COMPANY_ADDRESS",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 182, DateTimeKind.Utc).AddTicks(7292),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "Mussafah 44, Industrail Area"
                        },
                        new
                        {
                            Key = "COMPANY_TRN",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 182, DateTimeKind.Utc).AddTicks(7293),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "100366253100003"
                        },
                        new
                        {
                            Key = "COMPANY_PHONE",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 182, DateTimeKind.Utc).AddTicks(7294),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "+971 555298878"
                        },
                        new
                        {
                            Key = "CURRENCY",
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 182, DateTimeKind.Utc).AddTicks(7297),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "AED"
                        });
                });

            modelBuilder.Entity("FrozenApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 15, 13, 14, 15, 172, DateTimeKind.Utc).AddTicks(5485),
                            Email = "admin@starplus.com",
                            Name = "Admin",
                            PasswordHash = "$2a$11$2NrWEj1qE5TaBVDxya.pougj0VN2aLQDA8zyKKsh4i/MH1R.88AKa",
                            Phone = "+971 555 298 878",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("FrozenApi.Models.Alert", b =>
                {
                    b.HasOne("FrozenApi.Models.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("FrozenApi.Models.AuditLog", b =>
                {
                    b.HasOne("FrozenApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FrozenApi.Models.Expense", b =>
                {
                    b.HasOne("FrozenApi.Models.ExpenseCategory", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrozenApi.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("FrozenApi.Models.InventoryTransaction", b =>
                {
                    b.HasOne("FrozenApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FrozenApi.Models.InvoiceTemplate", b =>
                {
                    b.HasOne("FrozenApi.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("FrozenApi.Models.InvoiceVersion", b =>
                {
                    b.HasOne("FrozenApi.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrozenApi.Models.Sale", "Sale")
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("FrozenApi.Models.Payment", b =>
                {
                    b.HasOne("FrozenApi.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrozenApi.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("FrozenApi.Models.Sale", "Sale")
                        .WithMany()
                        .HasForeignKey("SaleId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("FrozenApi.Models.PaymentIdempotency", b =>
                {
                    b.HasOne("FrozenApi.Models.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrozenApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FrozenApi.Models.PriceChangeLog", b =>
                {
                    b.HasOne("FrozenApi.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrozenApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FrozenApi.Models.Purchase", b =>
                {
                    b.HasOne("FrozenApi.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("FrozenApi.Models.PurchaseItem", b =>
                {
                    b.HasOne("FrozenApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrozenApi.Models.Purchase", "Purchase")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("FrozenApi.Models.PurchaseReturn", b =>
                {
                    b.HasOne("FrozenApi.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrozenApi.Models.Purchase", "Purchase")
                        .WithMany()
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("FrozenApi.Models.PurchaseReturnItem", b =>
                {
                    b.HasOne("FrozenApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrozenApi.Models.PurchaseItem", "PurchaseItem")
                        .WithMany()
                        .HasForeignKey("PurchaseItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrozenApi.Models.PurchaseReturn", "PurchaseReturn")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseItem");

                    b.Navigation("PurchaseReturn");
                });

            modelBuilder.Entity("FrozenApi.Models.Sale", b =>
                {
                    b.HasOne("FrozenApi.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrozenApi.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("FrozenApi.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FrozenApi.Models.User", "LastModifiedByUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("DeletedByUser");

                    b.Navigation("LastModifiedByUser");
                });

            modelBuilder.Entity("FrozenApi.Models.SaleItem", b =>
                {
                    b.HasOne("FrozenApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrozenApi.Models.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("FrozenApi.Models.SaleReturn", b =>
                {
                    b.HasOne("FrozenApi.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrozenApi.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("FrozenApi.Models.Sale", "Sale")
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("FrozenApi.Models.SaleReturnItem", b =>
                {
                    b.HasOne("FrozenApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrozenApi.Models.SaleItem", "SaleItem")
                        .WithMany()
                        .HasForeignKey("SaleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrozenApi.Models.SaleReturn", "SaleReturn")
                        .WithMany("Items")
                        .HasForeignKey("SaleReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SaleItem");

                    b.Navigation("SaleReturn");
                });

            modelBuilder.Entity("FrozenApi.Models.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("FrozenApi.Models.Purchase", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FrozenApi.Models.PurchaseReturn", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FrozenApi.Models.Sale", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FrozenApi.Models.SaleReturn", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
